# Generated by Django 3.1.2 on 2020-12-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalchatroom', '0002_auto_20201223_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='parentMessage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generalchatroom.message'),
        ),
    ]
