# Generated by Django 3.1.2 on 2020-11-14 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='pl',
            name='topic',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='Link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='chatroomAvatar',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='chatroomName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='selected',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='selectedSub',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='selectedTopic',
            field=models.CharField(choices=[('App', 'App'), ('OS', 'OS'), ('PL', 'PL')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.DeleteModel(
            name='Os',
        ),
        migrations.DeleteModel(
            name='Pl',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
