# Generated by Django 3.1.2 on 2020-11-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20201114_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroomAvatar',
            field=models.FileField(null=True, upload_to='chatroomimages'),
        ),
    ]
