# Generated by Django 3.1.2 on 2020-11-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0003_auto_20201114_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroomAvatar',
            field=models.FileField(null=True, upload_to='chatroom_image'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registeration.user'),
            preserve_default=False,
        ),
    ]
