# Generated by Django 3.1.2 on 2020-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_auto_20201115_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroomAvatar',
            field=models.FileField(default='', upload_to='chatroom/image'),
            preserve_default=False,
        ),
    ]
