# Generated by Django 3.1.2 on 2020-11-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20201120_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='numberOfUser',
            field=models.IntegerField(default=1),
        ),
    ]
