# Generated by Django 3.1.2 on 2020-12-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='voteState',
            new_name='voteState_exxta',
        ),
    ]
