# Generated by Django 3.1.2 on 2020-12-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0002_auto_20201210_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='voteState_exxta',
            new_name='voteState',
        ),
    ]
