# Generated by Django 3.1.2 on 2020-12-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0004_auto_20201210_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='isVoted',
            new_name='voteState',
        ),
    ]
