# Generated by Django 3.1.2 on 2020-12-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0005_auto_20201210_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatroom_User',
        ),
    ]
