# Generated by Django 3.1.2 on 2020-11-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intrestedIn',
        ),
    ]
